site_name: My Docs

theme:
    feature:
        tabs: true
    language: ja
    name: material
    palette:
        accent: Green
        primary: Green

- plugins:
      - i18n:
            default_language: ja
            languages:
                ja: Japanese
                en: English
