site_name: SINETStream_md
site_url: https://onukiyuma.github.io/SINETStream_md/

theme:
    feature:
        tabs: true
    language: ja
    name: material
    palette:
        accent: Green
        primary: Green

plugins:
      - i18n:
            docs_structure: suffix
            fallback_to_default: true
            reconfigure_material: true
            reconfigure_search: true
            languages:
                - locale: ja
                  default: true
                  name: 日本語
                  build: true
                - locale: en
                  default: false
                  name: English
                  build: true
