name: Python application

on: push

jobs:
    build:
#        runs-on: ubuntu-latest
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

#            - name: Install Mkdocs
#              run: |
#                pip install mkdocs
#                pip install mkdocs-material
#                pip install mkdocs-static-i18n

            - name: Create LangPages
              run: python scripts/multi_langpage.py

            - name: Change Directory and List Files
              run: |
                cd site/news
                run: pwd
                run: ls -al

#            - name: List
#              run: ls -Ral
