name: Python application

on: push
#on: deployment

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
#            - name: Checkout
#              uses: actions/checkout@v2

#            - name: Install Mkdocs
#              run: |
#                pip install mkdocs
#                pip install mkdocs-material
#                pip install mkdocs-static-i18n

#            - name: Create LangPages
#              run: python scripts/multi_langpage.py

#            - name: Change Directory and List Files
#              run: |
#                cd docs/news
#                ls -al

#            - name: List
#              run: ls -Ral

            - name: Change Directory and List Files1
              run: |
                cd /home/runner/work/_temp/_github_workflow
                pwd
                ls -al

            - name: Change Directory and List Files2
              run: |
                cd /home/runner/work/_temp/_runner_file_commands
                pwd
                ls -al

            - name: Change Directory and List Files3
              run: |
                cd /home
                pwd
                ls -al
