name: Python application

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Create LangPages
              run: pip install mkdocs
              run: mkdocs python scripts/multi_langpage.py
