name: Python application

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install Mkdocs
              run: pip install mkdocs

            - name: Install Mkdocs-material
              run: pip install mkdocs-material

            - name: Install Mkdocs-static-i18n
              run: pip install mkdocs-static-i18n

#            - name: Checkout
#              uses: actions/checkout@v2

            - name: Create LangPages
              run: python scripts/multi_langpage.py
