name: Python application

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install Mkdocs
              run: pip install mkdocs

            - name: Create LangPages
              run: python /home/runner/work/SINETStream_md/scripts/multi_langpage.py
