name: Python application

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install Mkdocs
              run: pip install mkdocs

            - name: Checkout
              uses: actions/checkout@v2

            - name: Create LangPages
              run: python scripts/multi_langpage.py
