name: Deploy to GitHub Pages

on: 
  push:
    branches:
      - main

jobs:
  file-manipulation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main


      - name: Create LangPages
        run: python scripts/multi_langpage.py

      - name: Commit and Push Changes
        run: |
          git config user.name "y.onuki"
          git config user.email "onuki@nii.ac.jp"
          cd docs/news
          git add .
          git commit -m "Update files"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}