name: Python application

#on: push
on: deployment

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Mkdocs
              run: |
                pip install mkdocs
                pip install mkdocs-material
                pip install mkdocs-static-i18n

            - name: Create LangPages
              run: python scripts/multi_langpage.py

            - name: Change Directory and List Files
              run: |
                pwd
                cd docs
                pwd
                cd news
                ls -al

#            - name: List
#              run: ls -Ral
